### ISSUE TITLE
ne fonctionne pas avec nodejs v5.10.0

### ISSUE THREAD

**Issue by fensoft** [sigalou/jeedom_alexaapi#1]
Salut,

Pour info, voici l'erreur:
```
/var/www/html/plugins/alexaapi/resources/alexa-remote-http/cookie.js:1
(function (exports, require, module, __filename, __dirname) { let Alexa = require('./alexa-remote');
^^^
SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
at exports.runInThisContext (vm.js:53:16)
at Module._compile (module.js:387:25)
at Object.Module._extensions..js (module.js:422:10)
at Module.load (module.js:357:32)
at Function.Module._load (module.js:314:12)
at Function.Module.runMain (module.js:447:10)
at startup (node.js:146:18)
at node.js:404:3
```

Voici la partie utile d'un de mes plugins que j'ai mis dans mon script de dépendance:
```
BIN=`which node`
if [ "$BIN" = "" ]; then
  BIN=`which nodejs`
fi
if [ "$BIN" = "" ]; then
  echo "No nodejs found"
  major=0
else
  actual=`$BIN -v`
  major=`$BIN -v | sed "s#v##" | sed "s#[.].*##"`
  echo "Current version: ${actual} (major $major)"
fi

echo 30 > /tmp/maxcube_in_progress
if [ `arch` == "armv6l" -a $major -lt 5 ]; then
  echo "Raspberry 1 detected, using armv6 package"
  sudo npm rebuild
  sudo apt-get -y --purge autoremove nodejs npm
  sudo rm /etc/apt/sources.list.d/nodesource.list
  wget http://node-arm.herokuapp.com/node_latest_armhf.deb
  sudo dpkg -i node_latest_armhf.deb
  rm node_latest_armhf.deb
elif [ $major -lt 8 ]; then
  echo "using official repository"
  curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -
  sudo apt-get install -y nodejs npm
fi

BIN=`which node`
if [ "$BIN" = "" ]; then
  BIN=`which nodejs`
fi
new=`$BIN -v`;
echo "new version installed: ${new}"
```

N'hésite pas à t'en inspirer :)

**Comment by NebzHB** [comment]
J'ai fait une proposition sur base de ce que je fais aussi pour mes plugins, j'ai été un peu plus loin pour l'installation sur les mini et raspberry 1 en utilisant un package officiel à la place d'un package exotique.

**Comment by fensoft** [comment]
Yes on peux close !
